defmodule EctoShorts.Testing do
  @moduledoc since: "3.0.0"
  @moduledoc """
  Assertion helpers for testing Ecto queries and dynamic expressions.

  Use this module in your test files to make assertions about query
  structure and SQL output without relying on brittle string matching.
  The assertions compare queries at different levels (AST, inspect output,
  SQL) to give you flexibility in how you verify query construction.

  ## Assert queries and SQL

  Add `use EctoShorts.Testing` to your test module to get repo-bound
  helpers that delegate to this module:

      defmodule MyApp.QueryTest do
        use ExUnit.Case
        use EctoShorts.Testing, repo: MyApp.Repo

        test "filters by title" do
          q1 = from p in Post, where: p.title == ^"Hello"
          q2 = EctoShorts.CommonFilters.convert_params_to_filter(Post, %{title: "Hello"})
          assert_query(q1, q2)
        end
      end

  ## Available assertions

  * `assert_dynamic/2` - compare two `dynamic/2` expressions by their AST string.
  * `refute_dynamic/2` - assert two dynamic expressions are different.
  * `assert_query/2` - compare two `Ecto.Query` structs by their inspect form.
  * `refute_query/2` - assert two queries produce different inspect output.
  * `assert_sql/3-4` - compare the SQL generated by two queries.
  * `refute_sql/3-4` - assert two queries produce different SQL.

  When using `use EctoShorts.Testing`, the `:repo` option is bound at
  compile time, so `assert_sql/2-3` and `refute_sql/2-3` do not require
  an explicit repo argument.

  ## Testing strategies

  ### Strategy 1: Test query structure

  Use `assert_query/2` to verify that two queries have the same structure
  without executing them:

      test "builds correct query structure" do
        expected = from p in Post, where: p.published == ^true, limit: ^10
        actual = EctoShorts.CommonFilters.convert_params_to_filter(Post, %{published: true, limit: 10})
        assert_query(expected, actual)
      end

  This is fast and does not require a database connection.

  ### Strategy 2: Test SQL output

  Use `assert_sql/3` to verify that two queries generate the same SQL:

      test "generates correct SQL" do
        q1 = from p in Post, where: p.published == ^true
        q2 = EctoShorts.CommonFilters.convert_params_to_filter(Post, %{published: true})
        assert_sql(q1, q2)
      end

  This catches differences in how the query is compiled to SQL, but does
  not execute the query.

  ### Strategy 3: Test dynamic expressions

  Use `assert_dynamic/2` to verify that two dynamic expressions are identical:

      test "builds correct dynamic expression" do
        expected = dynamic([p], p.published == ^true)
        actual = EctoShorts.DynamicBuilders.convert_to_dynamic({:as, :post}, :published, {:==, true})
        assert_dynamic(expected, actual)
      end

  This is useful when testing expression builders directly.

  ## Choosing the right assertion

  Use this guide to pick the right assertion for your test:

  | Assertion         | When to use                                      |
  |-------------------|--------------------------------------------------|
  | `assert_query/2`  | Fast structure check without database            |
  | `assert_sql/3`    | Verify SQL output without executing              |
  | `assert_dynamic/2`| Test dynamic expression builders                 |
  | `refute_query/2`  | Verify two queries are different                 |
  | `refute_sql/3`    | Verify SQL output differs                        |
  | `refute_dynamic/2`| Verify dynamic expressions differ                |

  ### When to use `assert_query/2`

  * You want a fast test that does not require a database connection.
  * You are testing query construction logic, not SQL generation.
  * You want to verify the query structure matches exactly.

  ### When to use `assert_sql/3`

  * You want to verify the SQL output is correct.
  * You are testing database-specific features (for example, PostgreSQL
    array operators).
  * You want to catch differences in how Ecto compiles the query.

  ### When to use `assert_dynamic/2`

  * You are testing a custom dynamic expression builder.
  * You want to verify the AST structure of a dynamic expression.
  * You are testing `EctoShorts.DynamicBuilders` or a custom adapter.

  ## Testing complex queries

  ### Testing joins

  Verify that joins are added correctly:

      test "adds join correctly" do
        expected = from p in Post,
          join: c in assoc(p, :comments), as: :comment,
          where: c.approved == ^true

        actual = EctoShorts.CommonFilters.convert_params_to_filter(
          Post,
          %{comment: [as: :comment, approved: true]}
        )

        assert_query(expected, actual)
      end

  ### Testing subqueries

  Verify that subqueries are constructed correctly:

      test "builds subquery correctly" do
        expected = from p in Post,
          where: p.id in subquery(from c in Comment, select: c.post_id)

        actual = EctoShorts.CommonFilters.convert_params_to_filter(
          Post,
          %{id: %{in: %{all: from(c in Comment, select: c.post_id)}}}
        )

        assert_sql(expected, actual)
      end

  ### Testing aggregates

  Verify that aggregate expressions are correct:

      test "builds aggregate correctly" do
        expected = from p in Post,
          group_by: p.author_id,
          having: avg(p.views) > ^100

        actual = EctoShorts.CommonFilters.convert_params_to_filter(
          Post,
          %{group_by: :author_id, having: %{views: %{avg: %{>: 100}}}}
        )

        assert_query(expected, actual)
      end

  ## Common patterns

  **Pattern 1: Test multiple filter combinations**

  Use a table-driven approach to test many filter combinations:

      test "filters work correctly" do
        test_cases = [
          {%{published: true}, "WHERE published = TRUE"},
          {%{views: %{>: 10}}, "WHERE views > 10"},
          {%{title: %{like: "hello"}}, "WHERE title LIKE '%hello%'"}
        ]

        for {params, expected_sql} <- test_cases do
          query = EctoShorts.CommonFilters.convert_params_to_filter(Post, params)
          {sql, _} = Ecto.Adapters.SQL.to_sql(:all, Repo, query)
          assert sql =~ expected_sql
        end
      end

  **Pattern 2: Test error handling**

  Verify that invalid params are handled gracefully:

      test "handles invalid params gracefully" do
        query = EctoShorts.CommonFilters.convert_params_to_filter(
          Post,
          %{nonexistent_field: "value"}
        )

        # Should return unchanged query
        expected = from p in Post
        assert_query(expected, query)
      end

  **Pattern 3: Test SQL parameter binding**

  Verify that parameters are bound correctly:

      test "binds parameters correctly" do
        query = EctoShorts.CommonFilters.convert_params_to_filter(
          Post,
          %{title: "Hello", published: true}
        )

        {_sql, params} = Ecto.Adapters.SQL.to_sql(:all, Repo, query)
        assert params == ["Hello", true]
      end

  ## Troubleshooting

  **Problem:** `assert_query/2` fails but the queries look the same.

  **Solution:** The inspect output may differ due to variable names or
  internal query structure. Use `assert_sql/3` instead to compare the
  generated SQL.

  **Problem:** `assert_sql/3` fails with "no repo configured".

  **Solution:** Pass the repo explicitly as the first argument, or add
  `use EctoShorts.Testing, repo: MyApp.Repo` to bind the repo at compile time.

  **Problem:** `assert_dynamic/2` fails but the expressions look the same.

  **Solution:** The AST may differ due to variable names or internal
  structure. Use `IO.inspect/2` to see the actual AST of both expressions.

  **Problem:** SQL comparison fails due to whitespace differences.

  **Solution:** This should not happen as `assert_sql/3` compares the
  compiled SQL tuples directly. If it does, there may be a real difference
  in the SQL structure.

  See also `EctoShorts.CommonFilters`, `EctoShorts.DynamicBuilders`, and
  `EctoShorts.Actions`.
  """
  alias ExUnit.Assertions

  @doc """
  Asserts that two `dynamic/2` expressions are structurally identical.

  Compares both expressions by converting them to strings via
  `Macro.to_string/1`, which normalizes the AST. Calls `ExUnit.Assertions.flunk/1`
  with a diff when the expressions differ.

  Returns `:ok` on success.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.assert_dynamic(
      ...>   dynamic([p], p.id == 1),
      ...>   dynamic([p], p.id == 1)
      ...> )
      :ok

  See also `refute_dynamic/2` and `assert_query/2`.
  """
  def assert_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left !== right do
      Assertions.flunk(
        "Expected dynamic expressions to be equal:\n\nleft:  #{left}\nright: #{right}"
      )
    end

    :ok
  end

  @doc """
  Refutes that two `dynamic/2` expressions are structurally identical.

  Calls `ExUnit.Assertions.flunk/1` when the expressions produce the same
  `Macro.to_string/1` output. Returns `:ok` when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.refute_dynamic(
      ...>   dynamic([p], p.id == 1),
      ...>   dynamic([p], p.id == 2)
      ...> )
      :ok

  See also `assert_dynamic/2`.
  """
  def refute_dynamic(dyn_a, dyn_b) do
    left = Macro.to_string(dyn_a)
    right = Macro.to_string(dyn_b)

    if left === right do
      Assertions.flunk("Expected dynamic expressions to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  @doc """
  Asserts that two queries generate identical SQL strings using the given repo.

  Uses `Ecto.Adapters.SQL.to_sql/3` to compile each query and compares
  **only the SQL string** - bound parameter values are ignored. To also
  assert parameter values, use `Ecto.Adapters.SQL.to_sql/3` directly and
  compare the full `{sql, params}` tuple.

  `kind` is the SQL operation type (`:all`, `:update_all`, `:delete_all`);
  defaults to `:all`.

  ## Examples

      iex> import Ecto.Query
      ...> q1 = from p in EctoShorts.Schema.Post, where: p.id == ^1
      ...> q2 = EctoShorts.CommonFilters.convert_params_to_filter(EctoShorts.Schema.Post, %{id: 1})
      ...> EctoShorts.Testing.assert_sql(EctoShorts.Repo, q1, q2)
      :ok

  See also `refute_sql/4` and `assert_query/2`.
  """
  def assert_sql(repo, query_a, query_b, kind \\ :all) do
    {left, _} = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    {right, _} = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left !== right do
      Assertions.flunk(
        "Expected queries to produce the same SQL:\n\nleft:  #{inspect(left)}\nright: #{inspect(right)}"
      )
    end

    :ok
  end

  @doc """
  Refutes that two queries generate identical SQL strings using the given repo.

  Uses `Ecto.Adapters.SQL.to_sql/3` to compile each query and compares the
  full `{sql_string, params}` tuples (SQL string **and** bound parameters).
  Calls `ExUnit.Assertions.flunk/1` when both tuples match. Returns `:ok`
  when they differ.

  Note: unlike `assert_sql/4` which compares only the SQL string,
  `refute_sql/4` compares the full tuple including params.

  ## Examples

      iex> import Ecto.Query
      ...> q1 = from p in EctoShorts.Schema.Post, where: p.id == ^1
      ...> q2 = from p in EctoShorts.Schema.Post, where: p.id == ^2
      ...> EctoShorts.Testing.refute_sql(EctoShorts.Repo, q1, q2)
      :ok

  See also `assert_sql/4`.
  """
  def refute_sql(repo, query_a, query_b, kind \\ :all) do
    left = Ecto.Adapters.SQL.to_sql(kind, repo, query_a)
    right = Ecto.Adapters.SQL.to_sql(kind, repo, query_b)

    if left === right do
      Assertions.flunk(
        "Expected queries to produce different SQL, but both were:\n\n#{inspect(left)}"
      )
    end

    :ok
  end

  @doc """
  Asserts that two `Ecto.Query` structs are equal by comparing their inspect output.

  Uses the `Ecto.Query` inspect protocol to normalize both queries to strings.
  Calls `ExUnit.Assertions.flunk/1` with a diff when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.assert_query(
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1),
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1)
      ...> )
      :ok

  See also `refute_query/2` and `assert_sql/4`.
  """
  def assert_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left !== right do
      Assertions.flunk("Expected queries to be equal:\n\nleft:  #{left}\nright: #{right}")
    end

    :ok
  end

  @doc """
  Refutes that two `Ecto.Query` structs are equal.

  Calls `ExUnit.Assertions.flunk/1` when both queries produce the same
  inspect output. Returns `:ok` when they differ.

  ## Examples

      iex> import Ecto.Query
      ...> EctoShorts.Testing.refute_query(
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^1),
      ...>   from(p in EctoShorts.Schema.Post, where: p.id == ^2)
      ...> )
      :ok

  See also `assert_query/2`.
  """
  def refute_query(query_a, query_b) do
    left = inspect(query_a)
    right = inspect(query_b)

    if left === right do
      Assertions.flunk("Expected queries to be different, but both were:\n\n#{left}")
    end

    :ok
  end

  @doc """
  Injects repo-bound assertion helpers into the calling module.

  When you add `use EctoShorts.Testing, repo: MyApp.Repo` to a test module,
  the following 2-3 argument helpers are injected, with the repo bound at
  compile time:

  * `assert_dynamic/2` - delegates to `EctoShorts.Testing.assert_dynamic/2`.
  * `refute_dynamic/2` - delegates to `EctoShorts.Testing.refute_dynamic/2`.
  * `assert_query/2` - delegates to `EctoShorts.Testing.assert_query/2`.
  * `refute_query/2` - delegates to `EctoShorts.Testing.refute_query/2`.
  * `assert_sql/2-3` - delegates to `EctoShorts.Testing.assert_sql/4` with
    the bound repo. Signature: `assert_sql(query_a, query_b, kind \\\\ :all)`.
  * `refute_sql/2-3` - delegates to `EctoShorts.Testing.refute_sql/4` with
    the bound repo. Signature: `refute_sql(query_a, query_b, kind \\\\ :all)`.

  ## Options

    * `:repo` - the `Ecto.Repo` module to use. Defaults to
      `EctoShorts.Config.repo/0`.

  ## Example

      defmodule MyApp.QueryTest do
        use ExUnit.Case
        use EctoShorts.Testing, repo: MyApp.Repo

        test "filters by published" do
          q1 = from p in Post, where: p.published == ^true
          q2 = EctoShorts.CommonFilters.convert_params_to_filter(Post, %{published: true})
          assert_query(q1, q2)
          assert_sql(q1, q2)
        end
      end
  """
  defmacro __using__(opts) do
    quote do
      opts = unquote(opts)

      alias EctoShorts.Testing

      @repo Keyword.get(opts, :repo, EctoShorts.Config.repo())

      def assert_dynamic(dyn_a, dyn_b) do
        Testing.assert_dynamic(dyn_a, dyn_b)
      end

      def refute_dynamic(dyn_a, dyn_b) do
        Testing.refute_dynamic(dyn_a, dyn_b)
      end

      def assert_sql(query_a, query_b, kind \\ :all) do
        Testing.assert_sql(@repo, query_a, query_b, kind)
      end

      def refute_sql(query_a, query_b, kind \\ :all) do
        Testing.refute_sql(@repo, query_a, query_b, kind)
      end

      def assert_query(query_a, query_b) do
        Testing.assert_query(query_a, query_b)
      end

      def refute_query(query_a, query_b) do
        Testing.refute_query(query_a, query_b)
      end
    end
  end
end
