defmodule EctoShorts.Testing do
  @moduledoc """
  This API provides helpers to make testing easier in Ecto.

  This module provides macros to make it easier to write assertions
  when testing queries or dynamic expressions. These assertions work
  by comparing the string representations of Ecto queries, dynamic
  expressions, or the generated SQL output.

  It includes:

    * `assert_dynamic/2` – Compare two `dynamic/2` expressions by their AST.
    * `assert_query/2` – Compare two `Ecto.Query` structs by their stringified form.
    * `assert_sql/4` – Compare SQL output generated by queries.
    * `refute_*/2` versions – Inverse assertions to confirm inequality.
  """

  def insert!(repo, schema_source, params \\ %{}, opts \\ [])

  def insert!(repo, source, params, opts) when is_binary(source) do
    params = params |> Map.to_list() |> Enum.sort()

    keys = params |> Keyword.keys() |> Enum.map_join(", ", &to_string/1)
    values = Keyword.values(params)
    placeholders = Enum.map(0..Enum.count(keys), fn idx -> "$#{idx + 1}" end)

    Ecto.Adapters.SQL.query!(
      repo,
      "INSERT INTO #{source} (#{keys}) VALUES (#{placeholders})",
      values,
      opts
    )
  end

  def insert!(repo, {source, schema}, params, opts) do
    schema
    |> struct!()
    |> Ecto.put_meta(source: source)
    |> schema.changeset(params)
    |> repo.insert!(opts)
  end

  def insert!(repo, schema, params, opts) do
    schema
    |> struct!()
    |> schema.changeset(params)
    |> repo.insert!(opts)
  end

  @doc """
  Asserts that two `dynamic/2` expressions are structurally identical.

  It compares both expressions by converting them to strings using
  `Macro.to_string/1`, which normalizes their AST.

  ## Examples

      assert_dynamic(
        dynamic([p], p.id == 1),
        dynamic([p], p.id == 1)
      )
  """
  defmacro assert_dynamic(dyn_a, dyn_b) do
    quote do
      assert Macro.to_string(unquote(dyn_a)) === Macro.to_string(unquote(dyn_b))
    end
  end

  @doc """
  Refutes that two `dynamic/2` expressions are structurally identical.

  Uses `Macro.to_string/1` for comparison.

  ## Examples

      refute_dynamic(
        dynamic([p], p.id == 1),
        dynamic([p], p.id == 2)
      )
  """
  defmacro refute_dynamic(dyn_a, dyn_b) do
    quote do
      refute Macro.to_string(unquote(dyn_a)) === Macro.to_string(unquote(dyn_b))
    end
  end

  @doc """
  Asserts that two queries generate identical SQL using the given adapter and repo.

  This checks the actual SQL produced by Ecto using `Ecto.Adapters.SQL.to_sql/3`.

  ## Parameters

    * `repo` – The Ecto repo module.
    * `query_a`, `query_b` – The queries to compare.

  ## Examples

      assert_sql(Ecto.Adapters.Postgres, Repo, query1, query2)
  """
  defmacro assert_sql(repo, query_a, query_b) do
    quote do
      assert Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_a)) ===
               Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_b))
    end
  end

  @doc """
  Refutes that two queries generate identical SQL using the given repo.

  Useful when asserting that two queries should *not* compile to the same SQL.

  ## Examples

      refute_sql(Repo, query1, query2)
  """
  defmacro refute_sql(repo, query_a, query_b) do
    quote do
      refute Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_a)) ===
               Ecto.Adapters.SQL.to_sql(:all, unquote(repo), unquote(query_b))
    end
  end

  @doc """
  Asserts that two `Ecto.Query` structs are equal by comparing their string representation.

  Uses the `Ecto.Query` inspect protocol to convert the queries to strings.

  ## Examples

      assert_query(
        from(p in Post, where: p.id == 1),
        from(p in Post, where: p.id == 1)
      )
  """
  defmacro assert_query(query_a, query_b) do
    quote do
      assert inspect(unquote(query_a), pretty: true) === inspect(unquote(query_b), pretty: true)
    end
  end

  @doc """
  Refutes that two `Ecto.Query` structs are equal.

  Uses the `Ecto.Query` inspect protocol to convert the queries to strings.

  ## Examples

      refute_query(
        from(p in Post, where: p.id == 1),
        from(p in Post, where: p.id == 2)
      )
  """
  defmacro refute_query(query_a, query_b) do
    quote do
      refute inspect(unquote(query_a), pretty: true) === inspect(unquote(query_b), pretty: true)
    end
  end
end
