name: Dialyzer

on: push

jobs:
  dialyzer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
            dialyzer
          key: ${{ runner.os }}-mix-dialyzer-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-dialyzer-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.1.2
          elixir-version: 1.14.2
      - run: mix deps.get
      - run: mix dialyzer

